/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { UserWhereInput } from "./UserWhereInput";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserUpdateInput } from "./UserUpdateInput";
import { User } from "./User";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { ReportWhereUniqueInput } from "../../report/base/ReportWhereUniqueInput";
import { TeamUserFindManyArgs } from "../../teamUser/base/TeamUserFindManyArgs";
import { TeamUser } from "../../teamUser/base/TeamUser";
import { TeamUserWhereUniqueInput } from "../../teamUser/base/TeamUserWhereUniqueInput";
import { WebsiteFindManyArgs } from "../../website/base/WebsiteFindManyArgs";
import { Website } from "../../website/base/Website";
import { WebsiteWhereUniqueInput } from "../../website/base/WebsiteWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async create(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        role: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        role: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        deletedAt: true,
        id: true,
        role: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          role: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          deletedAt: true,
          id: true,
          role: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/report")
  @ApiNestedQuery(ReportFindManyArgs)
  async findManyReport(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Report[]> {
    const query = plainToClass(ReportFindManyArgs, request.query);
    const results = await this.service.findReport(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,
        parameters: true,
        typeField: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        website: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/report")
  async connectReport(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      report: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/report")
  async updateReport(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      report: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/report")
  async disconnectReport(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: ReportWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      report: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/teamUser")
  @ApiNestedQuery(TeamUserFindManyArgs)
  async findManyTeamUser(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<TeamUser[]> {
    const query = plainToClass(TeamUserFindManyArgs, request.query);
    const results = await this.service.findTeamUser(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        role: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teamUser")
  async connectTeamUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeamUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamUser: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teamUser")
  async updateTeamUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeamUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamUser: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teamUser")
  async disconnectTeamUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: TeamUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamUser: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/website")
  @ApiNestedQuery(WebsiteFindManyArgs)
  async findManyWebsite(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<Website[]> {
    const query = plainToClass(WebsiteFindManyArgs, request.query);
    const results = await this.service.findWebsite(params.id, {
      ...query,
      select: {
        createdAt: true,
        deletedAt: true,
        domain: true,
        id: true,
        name: true,
        resetAt: true,
        shareId: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/website")
  async connectWebsite(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WebsiteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      website: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/website")
  async updateWebsite(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WebsiteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      website: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/website")
  async disconnectWebsite(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: WebsiteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      website: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
