/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Person,
  Attribute,
  Display,
  Response,
  Session,
  Environment,
} from "@prisma/client";

export class PersonServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.PersonCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonCountArgs>
  ): Promise<number> {
    return this.prisma.person.count(args);
  }

  async findMany<T extends Prisma.PersonFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonFindManyArgs>
  ): Promise<Person[]> {
    return this.prisma.person.findMany(args);
  }
  async findOne<T extends Prisma.PersonFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonFindUniqueArgs>
  ): Promise<Person | null> {
    return this.prisma.person.findUnique(args);
  }
  async create<T extends Prisma.PersonCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonCreateArgs>
  ): Promise<Person> {
    return this.prisma.person.create<T>(args);
  }
  async update<T extends Prisma.PersonUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonUpdateArgs>
  ): Promise<Person> {
    return this.prisma.person.update<T>(args);
  }
  async delete<T extends Prisma.PersonDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PersonDeleteArgs>
  ): Promise<Person> {
    return this.prisma.person.delete(args);
  }

  async findAttributes(
    parentId: string,
    args: Prisma.AttributeFindManyArgs
  ): Promise<Attribute[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .attributes(args);
  }

  async findDisplays(
    parentId: string,
    args: Prisma.DisplayFindManyArgs
  ): Promise<Display[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .displays(args);
  }

  async findResponses(
    parentId: string,
    args: Prisma.ResponseFindManyArgs
  ): Promise<Response[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .responses(args);
  }

  async findSessions(
    parentId: string,
    args: Prisma.SessionFindManyArgs
  ): Promise<Session[]> {
    return this.prisma.person
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sessions(args);
  }

  async getEnvironment(parentId: string): Promise<Environment | null> {
    return this.prisma.person
      .findUnique({
        where: { id: parentId },
      })
      .environment();
  }
}
