/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePersonArgs } from "./CreatePersonArgs";
import { UpdatePersonArgs } from "./UpdatePersonArgs";
import { DeletePersonArgs } from "./DeletePersonArgs";
import { PersonCountArgs } from "./PersonCountArgs";
import { PersonFindManyArgs } from "./PersonFindManyArgs";
import { PersonFindUniqueArgs } from "./PersonFindUniqueArgs";
import { Person } from "./Person";
import { AttributeFindManyArgs } from "../../attribute/base/AttributeFindManyArgs";
import { Attribute } from "../../attribute/base/Attribute";
import { DisplayFindManyArgs } from "../../display/base/DisplayFindManyArgs";
import { Display } from "../../display/base/Display";
import { ResponseFindManyArgs } from "../../response/base/ResponseFindManyArgs";
import { Response } from "../../response/base/Response";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { Environment } from "../../environment/base/Environment";
import { PersonService } from "../person.service";
@graphql.Resolver(() => Person)
export class PersonResolverBase {
  constructor(protected readonly service: PersonService) {}

  async _peopleMeta(
    @graphql.Args() args: PersonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Person])
  async people(@graphql.Args() args: PersonFindManyArgs): Promise<Person[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Person, { nullable: true })
  async person(
    @graphql.Args() args: PersonFindUniqueArgs
  ): Promise<Person | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Person)
  async createPerson(@graphql.Args() args: CreatePersonArgs): Promise<Person> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        environment: {
          connect: args.data.environment,
        },
      },
    });
  }

  @graphql.Mutation(() => Person)
  async updatePerson(
    @graphql.Args() args: UpdatePersonArgs
  ): Promise<Person | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          environment: {
            connect: args.data.environment,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Person)
  async deletePerson(
    @graphql.Args() args: DeletePersonArgs
  ): Promise<Person | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Attribute], { name: "attributes" })
  async resolveFieldAttributes(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: AttributeFindManyArgs
  ): Promise<Attribute[]> {
    const results = await this.service.findAttributes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Display], { name: "displays" })
  async resolveFieldDisplays(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: DisplayFindManyArgs
  ): Promise<Display[]> {
    const results = await this.service.findDisplays(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Response], { name: "responses" })
  async resolveFieldResponses(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: ResponseFindManyArgs
  ): Promise<Response[]> {
    const results = await this.service.findResponses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Session], { name: "sessions" })
  async resolveFieldSessions(
    @graphql.Parent() parent: Person,
    @graphql.Args() args: SessionFindManyArgs
  ): Promise<Session[]> {
    const results = await this.service.findSessions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Environment, {
    nullable: true,
    name: "environment",
  })
  async resolveFieldEnvironment(
    @graphql.Parent() parent: Person
  ): Promise<Environment | null> {
    const result = await this.service.getEnvironment(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
