/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ApiKeyListRelationFilter } from "../../apiKey/base/ApiKeyListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AttributeClassListRelationFilter } from "../../attributeClass/base/AttributeClassListRelationFilter";
import { EventClassListRelationFilter } from "../../eventClass/base/EventClassListRelationFilter";
import { PersonListRelationFilter } from "../../person/base/PersonListRelationFilter";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { SurveyListRelationFilter } from "../../survey/base/SurveyListRelationFilter";
import { TagListRelationFilter } from "../../tag/base/TagListRelationFilter";
import { WebhookListRelationFilter } from "../../webhook/base/WebhookListRelationFilter";

@InputType()
class EnvironmentWhereInput {
  @ApiProperty({
    required: false,
    type: () => ApiKeyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ApiKeyListRelationFilter)
  @IsOptional()
  @Field(() => ApiKeyListRelationFilter, {
    nullable: true,
  })
  apiKeys?: ApiKeyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AttributeClassListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AttributeClassListRelationFilter)
  @IsOptional()
  @Field(() => AttributeClassListRelationFilter, {
    nullable: true,
  })
  attributeClasses?: AttributeClassListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EventClassListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EventClassListRelationFilter)
  @IsOptional()
  @Field(() => EventClassListRelationFilter, {
    nullable: true,
  })
  eventClasses?: EventClassListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => PersonListRelationFilter,
  })
  @ValidateNested()
  @Type(() => PersonListRelationFilter)
  @IsOptional()
  @Field(() => PersonListRelationFilter, {
    nullable: true,
  })
  people?: PersonListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => SurveyListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SurveyListRelationFilter)
  @IsOptional()
  @Field(() => SurveyListRelationFilter, {
    nullable: true,
  })
  surveys?: SurveyListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TagListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TagListRelationFilter)
  @IsOptional()
  @Field(() => TagListRelationFilter, {
    nullable: true,
  })
  tags?: TagListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WebhookListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WebhookListRelationFilter)
  @IsOptional()
  @Field(() => WebhookListRelationFilter, {
    nullable: true,
  })
  webhooks?: WebhookListRelationFilter;
}

export { EnvironmentWhereInput as EnvironmentWhereInput };
