/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateEnvironmentArgs } from "./CreateEnvironmentArgs";
import { UpdateEnvironmentArgs } from "./UpdateEnvironmentArgs";
import { DeleteEnvironmentArgs } from "./DeleteEnvironmentArgs";
import { EnvironmentCountArgs } from "./EnvironmentCountArgs";
import { EnvironmentFindManyArgs } from "./EnvironmentFindManyArgs";
import { EnvironmentFindUniqueArgs } from "./EnvironmentFindUniqueArgs";
import { Environment } from "./Environment";
import { ApiKeyFindManyArgs } from "../../apiKey/base/ApiKeyFindManyArgs";
import { ApiKey } from "../../apiKey/base/ApiKey";
import { AttributeClassFindManyArgs } from "../../attributeClass/base/AttributeClassFindManyArgs";
import { AttributeClass } from "../../attributeClass/base/AttributeClass";
import { EventClassFindManyArgs } from "../../eventClass/base/EventClassFindManyArgs";
import { EventClass } from "../../eventClass/base/EventClass";
import { PersonFindManyArgs } from "../../person/base/PersonFindManyArgs";
import { Person } from "../../person/base/Person";
import { SurveyFindManyArgs } from "../../survey/base/SurveyFindManyArgs";
import { Survey } from "../../survey/base/Survey";
import { TagFindManyArgs } from "../../tag/base/TagFindManyArgs";
import { Tag } from "../../tag/base/Tag";
import { WebhookFindManyArgs } from "../../webhook/base/WebhookFindManyArgs";
import { Webhook } from "../../webhook/base/Webhook";
import { Product } from "../../product/base/Product";
import { EnvironmentService } from "../environment.service";
@graphql.Resolver(() => Environment)
export class EnvironmentResolverBase {
  constructor(protected readonly service: EnvironmentService) {}

  async _environmentsMeta(
    @graphql.Args() args: EnvironmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Environment])
  async environments(
    @graphql.Args() args: EnvironmentFindManyArgs
  ): Promise<Environment[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Environment, { nullable: true })
  async environment(
    @graphql.Args() args: EnvironmentFindUniqueArgs
  ): Promise<Environment | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Environment)
  async createEnvironment(
    @graphql.Args() args: CreateEnvironmentArgs
  ): Promise<Environment> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        product: {
          connect: args.data.product,
        },
      },
    });
  }

  @graphql.Mutation(() => Environment)
  async updateEnvironment(
    @graphql.Args() args: UpdateEnvironmentArgs
  ): Promise<Environment | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          product: {
            connect: args.data.product,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Environment)
  async deleteEnvironment(
    @graphql.Args() args: DeleteEnvironmentArgs
  ): Promise<Environment | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [ApiKey], { name: "apiKeys" })
  async resolveFieldApiKeys(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: ApiKeyFindManyArgs
  ): Promise<ApiKey[]> {
    const results = await this.service.findApiKeys(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [AttributeClass], { name: "attributeClasses" })
  async resolveFieldAttributeClasses(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: AttributeClassFindManyArgs
  ): Promise<AttributeClass[]> {
    const results = await this.service.findAttributeClasses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [EventClass], { name: "eventClasses" })
  async resolveFieldEventClasses(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: EventClassFindManyArgs
  ): Promise<EventClass[]> {
    const results = await this.service.findEventClasses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Person], { name: "people" })
  async resolveFieldPeople(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: PersonFindManyArgs
  ): Promise<Person[]> {
    const results = await this.service.findPeople(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Survey], { name: "surveys" })
  async resolveFieldSurveys(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: SurveyFindManyArgs
  ): Promise<Survey[]> {
    const results = await this.service.findSurveys(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Tag], { name: "tags" })
  async resolveFieldTags(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: TagFindManyArgs
  ): Promise<Tag[]> {
    const results = await this.service.findTags(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Webhook], { name: "webhooks" })
  async resolveFieldWebhooks(
    @graphql.Parent() parent: Environment,
    @graphql.Args() args: WebhookFindManyArgs
  ): Promise<Webhook[]> {
    const results = await this.service.findWebhooks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async resolveFieldProduct(
    @graphql.Parent() parent: Environment
  ): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
