/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Website,
  EventDatum,
  Report,
  SessionDatum,
  TeamWebsite,
  User,
} from "@prisma/client";

export class WebsiteServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.WebsiteCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebsiteCountArgs>
  ): Promise<number> {
    return this.prisma.website.count(args);
  }

  async findMany<T extends Prisma.WebsiteFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebsiteFindManyArgs>
  ): Promise<Website[]> {
    return this.prisma.website.findMany(args);
  }
  async findOne<T extends Prisma.WebsiteFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebsiteFindUniqueArgs>
  ): Promise<Website | null> {
    return this.prisma.website.findUnique(args);
  }
  async create<T extends Prisma.WebsiteCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebsiteCreateArgs>
  ): Promise<Website> {
    return this.prisma.website.create<T>(args);
  }
  async update<T extends Prisma.WebsiteUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebsiteUpdateArgs>
  ): Promise<Website> {
    return this.prisma.website.update<T>(args);
  }
  async delete<T extends Prisma.WebsiteDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.WebsiteDeleteArgs>
  ): Promise<Website> {
    return this.prisma.website.delete(args);
  }

  async findEventData(
    parentId: string,
    args: Prisma.EventDatumFindManyArgs
  ): Promise<EventDatum[]> {
    return this.prisma.website
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .eventData(args);
  }

  async findReport(
    parentId: string,
    args: Prisma.ReportFindManyArgs
  ): Promise<Report[]> {
    return this.prisma.website
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .report(args);
  }

  async findSessionData(
    parentId: string,
    args: Prisma.SessionDatumFindManyArgs
  ): Promise<SessionDatum[]> {
    return this.prisma.website
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .sessionData(args);
  }

  async findTeamWebsite(
    parentId: string,
    args: Prisma.TeamWebsiteFindManyArgs
  ): Promise<TeamWebsite[]> {
    return this.prisma.website
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .teamWebsite(args);
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.website
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
