/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateSessionArgs } from "./CreateSessionArgs";
import { UpdateSessionArgs } from "./UpdateSessionArgs";
import { DeleteSessionArgs } from "./DeleteSessionArgs";
import { SessionCountArgs } from "./SessionCountArgs";
import { SessionFindManyArgs } from "./SessionFindManyArgs";
import { SessionFindUniqueArgs } from "./SessionFindUniqueArgs";
import { Session } from "./Session";
import { EventFindManyArgs } from "../../event/base/EventFindManyArgs";
import { Event } from "../../event/base/Event";
import { Person } from "../../person/base/Person";
import { SessionService } from "../session.service";
@graphql.Resolver(() => Session)
export class SessionResolverBase {
  constructor(protected readonly service: SessionService) {}

  async _sessionsMeta(
    @graphql.Args() args: SessionCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Session])
  async sessions(
    @graphql.Args() args: SessionFindManyArgs
  ): Promise<Session[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Session, { nullable: true })
  async session(
    @graphql.Args() args: SessionFindUniqueArgs
  ): Promise<Session | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Session)
  async createSession(
    @graphql.Args() args: CreateSessionArgs
  ): Promise<Session> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        person: {
          connect: args.data.person,
        },
      },
    });
  }

  @graphql.Mutation(() => Session)
  async updateSession(
    @graphql.Args() args: UpdateSessionArgs
  ): Promise<Session | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          person: {
            connect: args.data.person,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Session)
  async deleteSession(
    @graphql.Args() args: DeleteSessionArgs
  ): Promise<Session | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Event], { name: "events" })
  async resolveFieldEvents(
    @graphql.Parent() parent: Session,
    @graphql.Args() args: EventFindManyArgs
  ): Promise<Event[]> {
    const results = await this.service.findEvents(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Person, {
    nullable: true,
    name: "person",
  })
  async resolveFieldPerson(
    @graphql.Parent() parent: Session
  ): Promise<Person | null> {
    const result = await this.service.getPerson(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
