/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProductService } from "../product.service";
import { ProductCreateInput } from "./ProductCreateInput";
import { ProductWhereInput } from "./ProductWhereInput";
import { ProductWhereUniqueInput } from "./ProductWhereUniqueInput";
import { ProductFindManyArgs } from "./ProductFindManyArgs";
import { ProductUpdateInput } from "./ProductUpdateInput";
import { Product } from "./Product";
import { EnvironmentFindManyArgs } from "../../environment/base/EnvironmentFindManyArgs";
import { Environment } from "../../environment/base/Environment";
import { EnvironmentWhereUniqueInput } from "../../environment/base/EnvironmentWhereUniqueInput";

export class ProductControllerBase {
  constructor(protected readonly service: ProductService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Product })
  async create(@common.Body() data: ProductCreateInput): Promise<Product> {
    return await this.service.create({
      data: {
        ...data,

        team: {
          connect: data.team,
        },
      },
      select: {
        brandColor: true,
        clickOutsideClose: true,
        createdAt: true,
        darkOverlay: true,
        formbricksSignature: true,
        highlightBorderColor: true,
        id: true,
        name: true,
        placement: true,
        recontactDays: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Product] })
  @ApiNestedQuery(ProductFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Product[]> {
    const args = plainToClass(ProductFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        brandColor: true,
        clickOutsideClose: true,
        createdAt: true,
        darkOverlay: true,
        formbricksSignature: true,
        highlightBorderColor: true,
        id: true,
        name: true,
        placement: true,
        recontactDays: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        brandColor: true,
        clickOutsideClose: true,
        createdAt: true,
        darkOverlay: true,
        formbricksSignature: true,
        highlightBorderColor: true,
        id: true,
        name: true,
        placement: true,
        recontactDays: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() data: ProductUpdateInput
  ): Promise<Product | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          team: {
            connect: data.team,
          },
        },
        select: {
          brandColor: true,
          clickOutsideClose: true,
          createdAt: true,
          darkOverlay: true,
          formbricksSignature: true,
          highlightBorderColor: true,
          id: true,
          name: true,
          placement: true,
          recontactDays: true,

          team: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Product })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Product | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          brandColor: true,
          clickOutsideClose: true,
          createdAt: true,
          darkOverlay: true,
          formbricksSignature: true,
          highlightBorderColor: true,
          id: true,
          name: true,
          placement: true,
          recontactDays: true,

          team: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/environments")
  @ApiNestedQuery(EnvironmentFindManyArgs)
  async findManyEnvironments(
    @common.Req() request: Request,
    @common.Param() params: ProductWhereUniqueInput
  ): Promise<Environment[]> {
    const query = plainToClass(EnvironmentFindManyArgs, request.query);
    const results = await this.service.findEnvironments(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        product: {
          select: {
            id: true,
          },
        },

        type: true,
        updatedAt: true,
        widgetSetupCompleted: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/environments")
  async connectEnvironments(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: EnvironmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      environments: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/environments")
  async updateEnvironments(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: EnvironmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      environments: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/environments")
  async disconnectEnvironments(
    @common.Param() params: ProductWhereUniqueInput,
    @common.Body() body: EnvironmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      environments: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
