/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TeamService } from "../team.service";
import { TeamCreateInput } from "./TeamCreateInput";
import { TeamWhereInput } from "./TeamWhereInput";
import { TeamWhereUniqueInput } from "./TeamWhereUniqueInput";
import { TeamFindManyArgs } from "./TeamFindManyArgs";
import { TeamUpdateInput } from "./TeamUpdateInput";
import { Team } from "./Team";
import { TeamUserFindManyArgs } from "../../teamUser/base/TeamUserFindManyArgs";
import { TeamUser } from "../../teamUser/base/TeamUser";
import { TeamUserWhereUniqueInput } from "../../teamUser/base/TeamUserWhereUniqueInput";
import { TeamWebsiteFindManyArgs } from "../../teamWebsite/base/TeamWebsiteFindManyArgs";
import { TeamWebsite } from "../../teamWebsite/base/TeamWebsite";
import { TeamWebsiteWhereUniqueInput } from "../../teamWebsite/base/TeamWebsiteWhereUniqueInput";

export class TeamControllerBase {
  constructor(protected readonly service: TeamService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Team })
  async create(@common.Body() data: TeamCreateInput): Promise<Team> {
    return await this.service.create({
      data: data,
      select: {
        accessCode: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Team] })
  @ApiNestedQuery(TeamFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Team[]> {
    const args = plainToClass(TeamFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        accessCode: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Team })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<Team | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        accessCode: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Team })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() data: TeamUpdateInput
  ): Promise<Team | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          accessCode: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Team })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<Team | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          accessCode: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/teamUser")
  @ApiNestedQuery(TeamUserFindManyArgs)
  async findManyTeamUser(
    @common.Req() request: Request,
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<TeamUser[]> {
    const query = plainToClass(TeamUserFindManyArgs, request.query);
    const results = await this.service.findTeamUser(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        role: true,

        team: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teamUser")
  async connectTeamUser(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamUser: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teamUser")
  async updateTeamUser(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamUser: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teamUser")
  async disconnectTeamUser(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamUserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamUser: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/teamWebsite")
  @ApiNestedQuery(TeamWebsiteFindManyArgs)
  async findManyTeamWebsite(
    @common.Req() request: Request,
    @common.Param() params: TeamWhereUniqueInput
  ): Promise<TeamWebsite[]> {
    const query = plainToClass(TeamWebsiteFindManyArgs, request.query);
    const results = await this.service.findTeamWebsite(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        team: {
          select: {
            id: true,
          },
        },

        website: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/teamWebsite")
  async connectTeamWebsite(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamWebsiteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamWebsite: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/teamWebsite")
  async updateTeamWebsite(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamWebsiteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamWebsite: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/teamWebsite")
  async disconnectTeamWebsite(
    @common.Param() params: TeamWhereUniqueInput,
    @common.Body() body: TeamWebsiteWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      teamWebsite: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
