/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { SessionDatumCreateNestedManyWithoutSessionsInput } from "./SessionDatumCreateNestedManyWithoutSessionsInput";
import { Type } from "class-transformer";
import { WebsiteEventCreateNestedManyWithoutSessionsInput } from "./WebsiteEventCreateNestedManyWithoutSessionsInput";

@InputType()
class SessionCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  browser?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  device?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  hostname?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  language?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  os?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  screen?: string | null;

  @ApiProperty({
    required: false,
    type: () => SessionDatumCreateNestedManyWithoutSessionsInput,
  })
  @ValidateNested()
  @Type(() => SessionDatumCreateNestedManyWithoutSessionsInput)
  @IsOptional()
  @Field(() => SessionDatumCreateNestedManyWithoutSessionsInput, {
    nullable: true,
  })
  sessionData?: SessionDatumCreateNestedManyWithoutSessionsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subdivision1?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  subdivision2?: string | null;

  @ApiProperty({
    required: false,
    type: () => WebsiteEventCreateNestedManyWithoutSessionsInput,
  })
  @ValidateNested()
  @Type(() => WebsiteEventCreateNestedManyWithoutSessionsInput)
  @IsOptional()
  @Field(() => WebsiteEventCreateNestedManyWithoutSessionsInput, {
    nullable: true,
  })
  websiteEvent?: WebsiteEventCreateNestedManyWithoutSessionsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  websiteId!: string;
}

export { SessionCreateInput as SessionCreateInput };
