/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { WebsiteEventService } from "../websiteEvent.service";
import { WebsiteEventCreateInput } from "./WebsiteEventCreateInput";
import { WebsiteEventWhereInput } from "./WebsiteEventWhereInput";
import { WebsiteEventWhereUniqueInput } from "./WebsiteEventWhereUniqueInput";
import { WebsiteEventFindManyArgs } from "./WebsiteEventFindManyArgs";
import { WebsiteEventUpdateInput } from "./WebsiteEventUpdateInput";
import { WebsiteEvent } from "./WebsiteEvent";
import { EventDatumFindManyArgs } from "../../eventDatum/base/EventDatumFindManyArgs";
import { EventDatum } from "../../eventDatum/base/EventDatum";
import { EventDatumWhereUniqueInput } from "../../eventDatum/base/EventDatumWhereUniqueInput";

export class WebsiteEventControllerBase {
  constructor(protected readonly service: WebsiteEventService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WebsiteEvent })
  async create(
    @common.Body() data: WebsiteEventCreateInput
  ): Promise<WebsiteEvent> {
    return await this.service.create({
      data: {
        ...data,

        session: {
          connect: data.session,
        },
      },
      select: {
        createdAt: true,
        eventName: true,
        eventType: true,
        id: true,
        pageTitle: true,
        referrerDomain: true,
        referrerPath: true,
        referrerQuery: true,

        session: {
          select: {
            id: true,
          },
        },

        urlPath: true,
        urlQuery: true,
        websiteId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [WebsiteEvent] })
  @ApiNestedQuery(WebsiteEventFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<WebsiteEvent[]> {
    const args = plainToClass(WebsiteEventFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        eventName: true,
        eventType: true,
        id: true,
        pageTitle: true,
        referrerDomain: true,
        referrerPath: true,
        referrerQuery: true,

        session: {
          select: {
            id: true,
          },
        },

        urlPath: true,
        urlQuery: true,
        websiteId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WebsiteEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: WebsiteEventWhereUniqueInput
  ): Promise<WebsiteEvent | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        eventName: true,
        eventType: true,
        id: true,
        pageTitle: true,
        referrerDomain: true,
        referrerPath: true,
        referrerQuery: true,

        session: {
          select: {
            id: true,
          },
        },

        urlPath: true,
        urlQuery: true,
        websiteId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WebsiteEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: WebsiteEventWhereUniqueInput,
    @common.Body() data: WebsiteEventUpdateInput
  ): Promise<WebsiteEvent | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          session: {
            connect: data.session,
          },
        },
        select: {
          createdAt: true,
          eventName: true,
          eventType: true,
          id: true,
          pageTitle: true,
          referrerDomain: true,
          referrerPath: true,
          referrerQuery: true,

          session: {
            select: {
              id: true,
            },
          },

          urlPath: true,
          urlQuery: true,
          websiteId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WebsiteEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: WebsiteEventWhereUniqueInput
  ): Promise<WebsiteEvent | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          eventName: true,
          eventType: true,
          id: true,
          pageTitle: true,
          referrerDomain: true,
          referrerPath: true,
          referrerQuery: true,

          session: {
            select: {
              id: true,
            },
          },

          urlPath: true,
          urlQuery: true,
          websiteId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/eventData")
  @ApiNestedQuery(EventDatumFindManyArgs)
  async findManyEventData(
    @common.Req() request: Request,
    @common.Param() params: WebsiteEventWhereUniqueInput
  ): Promise<EventDatum[]> {
    const query = plainToClass(EventDatumFindManyArgs, request.query);
    const results = await this.service.findEventData(params.id, {
      ...query,
      select: {
        createdAt: true,
        dataType: true,
        dateValue: true,
        eventKey: true,
        id: true,
        numberValue: true,
        stringValue: true,

        website: {
          select: {
            id: true,
          },
        },

        websiteEvent: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/eventData")
  async connectEventData(
    @common.Param() params: WebsiteEventWhereUniqueInput,
    @common.Body() body: EventDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      eventData: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/eventData")
  async updateEventData(
    @common.Param() params: WebsiteEventWhereUniqueInput,
    @common.Body() body: EventDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      eventData: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/eventData")
  async disconnectEventData(
    @common.Param() params: WebsiteEventWhereUniqueInput,
    @common.Body() body: EventDatumWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      eventData: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
